/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedMfaSetupRouteImport } from './routes/_authenticated/mfa-setup'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedSbirIndexRouteImport } from './routes/_authenticated/sbir/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedFinancialIndexRouteImport } from './routes/_authenticated/financial/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated/compliance/index'
import { Route as PublicOauthCallbackRouteImport } from './routes/_public/oauth/callback'
import { Route as AuthenticatedSbirAwardsRouteImport } from './routes/_authenticated/sbir/awards'
import { Route as AuthenticatedReportsBuilderRouteImport } from './routes/_authenticated/reports/builder'
import { Route as AuthenticatedPortalSprintsRouteImport } from './routes/_authenticated/portal/sprints'
import { Route as AuthenticatedPortalScopeRouteImport } from './routes/_authenticated/portal/scope'
import { Route as AuthenticatedPortalMilestonesRouteImport } from './routes/_authenticated/portal/milestones'
import { Route as AuthenticatedPortalMessagingRouteImport } from './routes/_authenticated/portal/messaging'
import { Route as AuthenticatedPortalFeaturesRouteImport } from './routes/_authenticated/portal/features'
import { Route as AuthenticatedOpportunitiesSourcesSoughtRouteImport } from './routes/_authenticated/opportunities/sources-sought'
import { Route as AuthenticatedOpportunitiesSolicitationRouteImport } from './routes/_authenticated/opportunities/solicitation'
import { Route as AuthenticatedOpportunitiesPresolicitationRouteImport } from './routes/_authenticated/opportunities/presolicitation'
import { Route as AuthenticatedOpportunitiesMapRouteImport } from './routes/_authenticated/opportunities/map'
import { Route as AuthenticatedNaicsNaicsCodeRouteImport } from './routes/_authenticated/naics/$naicsCode'
import { Route as AuthenticatedFinancialLaborRatesRouteImport } from './routes/_authenticated/financial/labor-rates'
import { Route as AuthenticatedCrmOrganizationsRouteImport } from './routes/_authenticated/crm/organizations'
import { Route as AuthenticatedCrmInteractionsRouteImport } from './routes/_authenticated/crm/interactions'
import { Route as AuthenticatedCrmContactsRouteImport } from './routes/_authenticated/crm/contacts'
import { Route as AuthenticatedContractsContractIdRouteImport } from './routes/_authenticated/contracts/$contractId'
import { Route as AuthenticatedComplianceSbomRouteImport } from './routes/_authenticated/compliance/sbom'
import { Route as AuthenticatedComplianceClearancesRouteImport } from './routes/_authenticated/compliance/clearances'
import { Route as AuthenticatedAdminUserRolesRouteImport } from './routes/_authenticated/admin/user-roles'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedFinancialInvoicesIndexRouteImport } from './routes/_authenticated/financial/invoices/index'
import { Route as AuthenticatedFinancialBudgetsIndexRouteImport } from './routes/_authenticated/financial/budgets/index'
import { Route as AuthenticatedComplianceCertificationsIndexRouteImport } from './routes/_authenticated/compliance/certifications/index'
import { Route as AuthenticatedFinancialInvoicesInvoiceIdRouteImport } from './routes/_authenticated/financial/invoices/$invoiceId'
import { Route as AuthenticatedFinancialBudgetsBudgetIdRouteImport } from './routes/_authenticated/financial/budgets/$budgetId'
import { Route as AuthenticatedComplianceCertificationsCertificationIdRouteImport } from './routes/_authenticated/compliance/certifications/$certificationId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMfaSetupRoute = AuthenticatedMfaSetupRouteImport.update({
  id: '/mfa-setup',
  path: '/mfa-setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSbirIndexRoute = AuthenticatedSbirIndexRouteImport.update({
  id: '/sbir/',
  path: '/sbir/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialIndexRoute =
  AuthenticatedFinancialIndexRouteImport.update({
    id: '/financial/',
    path: '/financial/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/compliance/',
    path: '/compliance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicOauthCallbackRoute = PublicOauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedSbirAwardsRoute = AuthenticatedSbirAwardsRouteImport.update({
  id: '/sbir/awards',
  path: '/sbir/awards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsBuilderRoute =
  AuthenticatedReportsBuilderRouteImport.update({
    id: '/reports/builder',
    path: '/reports/builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalSprintsRoute =
  AuthenticatedPortalSprintsRouteImport.update({
    id: '/portal/sprints',
    path: '/portal/sprints',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalScopeRoute =
  AuthenticatedPortalScopeRouteImport.update({
    id: '/portal/scope',
    path: '/portal/scope',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalMilestonesRoute =
  AuthenticatedPortalMilestonesRouteImport.update({
    id: '/portal/milestones',
    path: '/portal/milestones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalMessagingRoute =
  AuthenticatedPortalMessagingRouteImport.update({
    id: '/portal/messaging',
    path: '/portal/messaging',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalFeaturesRoute =
  AuthenticatedPortalFeaturesRouteImport.update({
    id: '/portal/features',
    path: '/portal/features',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpportunitiesSourcesSoughtRoute =
  AuthenticatedOpportunitiesSourcesSoughtRouteImport.update({
    id: '/sources-sought',
    path: '/sources-sought',
    getParentRoute: () => AuthenticatedOpportunitiesRoute,
  } as any)
const AuthenticatedOpportunitiesSolicitationRoute =
  AuthenticatedOpportunitiesSolicitationRouteImport.update({
    id: '/solicitation',
    path: '/solicitation',
    getParentRoute: () => AuthenticatedOpportunitiesRoute,
  } as any)
const AuthenticatedOpportunitiesPresolicitationRoute =
  AuthenticatedOpportunitiesPresolicitationRouteImport.update({
    id: '/presolicitation',
    path: '/presolicitation',
    getParentRoute: () => AuthenticatedOpportunitiesRoute,
  } as any)
const AuthenticatedOpportunitiesMapRoute =
  AuthenticatedOpportunitiesMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => AuthenticatedOpportunitiesRoute,
  } as any)
const AuthenticatedNaicsNaicsCodeRoute =
  AuthenticatedNaicsNaicsCodeRouteImport.update({
    id: '/naics/$naicsCode',
    path: '/naics/$naicsCode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialLaborRatesRoute =
  AuthenticatedFinancialLaborRatesRouteImport.update({
    id: '/financial/labor-rates',
    path: '/financial/labor-rates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmOrganizationsRoute =
  AuthenticatedCrmOrganizationsRouteImport.update({
    id: '/crm/organizations',
    path: '/crm/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmInteractionsRoute =
  AuthenticatedCrmInteractionsRouteImport.update({
    id: '/crm/interactions',
    path: '/crm/interactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmContactsRoute =
  AuthenticatedCrmContactsRouteImport.update({
    id: '/crm/contacts',
    path: '/crm/contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsContractIdRoute =
  AuthenticatedContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceSbomRoute =
  AuthenticatedComplianceSbomRouteImport.update({
    id: '/compliance/sbom',
    path: '/compliance/sbom',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceClearancesRoute =
  AuthenticatedComplianceClearancesRouteImport.update({
    id: '/compliance/clearances',
    path: '/compliance/clearances',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUserRolesRoute =
  AuthenticatedAdminUserRolesRouteImport.update({
    id: '/admin/user-roles',
    path: '/admin/user-roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialInvoicesIndexRoute =
  AuthenticatedFinancialInvoicesIndexRouteImport.update({
    id: '/financial/invoices/',
    path: '/financial/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialBudgetsIndexRoute =
  AuthenticatedFinancialBudgetsIndexRouteImport.update({
    id: '/financial/budgets/',
    path: '/financial/budgets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceCertificationsIndexRoute =
  AuthenticatedComplianceCertificationsIndexRouteImport.update({
    id: '/compliance/certifications/',
    path: '/compliance/certifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialInvoicesInvoiceIdRoute =
  AuthenticatedFinancialInvoicesInvoiceIdRouteImport.update({
    id: '/financial/invoices/$invoiceId',
    path: '/financial/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialBudgetsBudgetIdRoute =
  AuthenticatedFinancialBudgetsBudgetIdRouteImport.update({
    id: '/financial/budgets/$budgetId',
    path: '/financial/budgets/$budgetId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceCertificationsCertificationIdRoute =
  AuthenticatedComplianceCertificationsCertificationIdRouteImport.update({
    id: '/compliance/certifications/$certificationId',
    path: '/compliance/certifications/$certificationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/mfa-setup': typeof AuthenticatedMfaSetupRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRouteWithChildren
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/user-roles': typeof AuthenticatedAdminUserRolesRoute
  '/compliance/clearances': typeof AuthenticatedComplianceClearancesRoute
  '/compliance/sbom': typeof AuthenticatedComplianceSbomRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/crm/interactions': typeof AuthenticatedCrmInteractionsRoute
  '/crm/organizations': typeof AuthenticatedCrmOrganizationsRoute
  '/financial/labor-rates': typeof AuthenticatedFinancialLaborRatesRoute
  '/naics/$naicsCode': typeof AuthenticatedNaicsNaicsCodeRoute
  '/opportunities/map': typeof AuthenticatedOpportunitiesMapRoute
  '/opportunities/presolicitation': typeof AuthenticatedOpportunitiesPresolicitationRoute
  '/opportunities/solicitation': typeof AuthenticatedOpportunitiesSolicitationRoute
  '/opportunities/sources-sought': typeof AuthenticatedOpportunitiesSourcesSoughtRoute
  '/portal/features': typeof AuthenticatedPortalFeaturesRoute
  '/portal/messaging': typeof AuthenticatedPortalMessagingRoute
  '/portal/milestones': typeof AuthenticatedPortalMilestonesRoute
  '/portal/scope': typeof AuthenticatedPortalScopeRoute
  '/portal/sprints': typeof AuthenticatedPortalSprintsRoute
  '/reports/builder': typeof AuthenticatedReportsBuilderRoute
  '/sbir/awards': typeof AuthenticatedSbirAwardsRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/financial/': typeof AuthenticatedFinancialIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/sbir/': typeof AuthenticatedSbirIndexRoute
  '/compliance/certifications/$certificationId': typeof AuthenticatedComplianceCertificationsCertificationIdRoute
  '/financial/budgets/$budgetId': typeof AuthenticatedFinancialBudgetsBudgetIdRoute
  '/financial/invoices/$invoiceId': typeof AuthenticatedFinancialInvoicesInvoiceIdRoute
  '/compliance/certifications/': typeof AuthenticatedComplianceCertificationsIndexRoute
  '/financial/budgets/': typeof AuthenticatedFinancialBudgetsIndexRoute
  '/financial/invoices/': typeof AuthenticatedFinancialInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/mfa-setup': typeof AuthenticatedMfaSetupRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRouteWithChildren
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/user-roles': typeof AuthenticatedAdminUserRolesRoute
  '/compliance/clearances': typeof AuthenticatedComplianceClearancesRoute
  '/compliance/sbom': typeof AuthenticatedComplianceSbomRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/crm/interactions': typeof AuthenticatedCrmInteractionsRoute
  '/crm/organizations': typeof AuthenticatedCrmOrganizationsRoute
  '/financial/labor-rates': typeof AuthenticatedFinancialLaborRatesRoute
  '/naics/$naicsCode': typeof AuthenticatedNaicsNaicsCodeRoute
  '/opportunities/map': typeof AuthenticatedOpportunitiesMapRoute
  '/opportunities/presolicitation': typeof AuthenticatedOpportunitiesPresolicitationRoute
  '/opportunities/solicitation': typeof AuthenticatedOpportunitiesSolicitationRoute
  '/opportunities/sources-sought': typeof AuthenticatedOpportunitiesSourcesSoughtRoute
  '/portal/features': typeof AuthenticatedPortalFeaturesRoute
  '/portal/messaging': typeof AuthenticatedPortalMessagingRoute
  '/portal/milestones': typeof AuthenticatedPortalMilestonesRoute
  '/portal/scope': typeof AuthenticatedPortalScopeRoute
  '/portal/sprints': typeof AuthenticatedPortalSprintsRoute
  '/reports/builder': typeof AuthenticatedReportsBuilderRoute
  '/sbir/awards': typeof AuthenticatedSbirAwardsRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/financial': typeof AuthenticatedFinancialIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/sbir': typeof AuthenticatedSbirIndexRoute
  '/compliance/certifications/$certificationId': typeof AuthenticatedComplianceCertificationsCertificationIdRoute
  '/financial/budgets/$budgetId': typeof AuthenticatedFinancialBudgetsBudgetIdRoute
  '/financial/invoices/$invoiceId': typeof AuthenticatedFinancialInvoicesInvoiceIdRoute
  '/compliance/certifications': typeof AuthenticatedComplianceCertificationsIndexRoute
  '/financial/budgets': typeof AuthenticatedFinancialBudgetsIndexRoute
  '/financial/invoices': typeof AuthenticatedFinancialInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/mfa-setup': typeof AuthenticatedMfaSetupRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRouteWithChildren
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/user-roles': typeof AuthenticatedAdminUserRolesRoute
  '/_authenticated/compliance/clearances': typeof AuthenticatedComplianceClearancesRoute
  '/_authenticated/compliance/sbom': typeof AuthenticatedComplianceSbomRoute
  '/_authenticated/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/_authenticated/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/_authenticated/crm/interactions': typeof AuthenticatedCrmInteractionsRoute
  '/_authenticated/crm/organizations': typeof AuthenticatedCrmOrganizationsRoute
  '/_authenticated/financial/labor-rates': typeof AuthenticatedFinancialLaborRatesRoute
  '/_authenticated/naics/$naicsCode': typeof AuthenticatedNaicsNaicsCodeRoute
  '/_authenticated/opportunities/map': typeof AuthenticatedOpportunitiesMapRoute
  '/_authenticated/opportunities/presolicitation': typeof AuthenticatedOpportunitiesPresolicitationRoute
  '/_authenticated/opportunities/solicitation': typeof AuthenticatedOpportunitiesSolicitationRoute
  '/_authenticated/opportunities/sources-sought': typeof AuthenticatedOpportunitiesSourcesSoughtRoute
  '/_authenticated/portal/features': typeof AuthenticatedPortalFeaturesRoute
  '/_authenticated/portal/messaging': typeof AuthenticatedPortalMessagingRoute
  '/_authenticated/portal/milestones': typeof AuthenticatedPortalMilestonesRoute
  '/_authenticated/portal/scope': typeof AuthenticatedPortalScopeRoute
  '/_authenticated/portal/sprints': typeof AuthenticatedPortalSprintsRoute
  '/_authenticated/reports/builder': typeof AuthenticatedReportsBuilderRoute
  '/_authenticated/sbir/awards': typeof AuthenticatedSbirAwardsRoute
  '/_public/oauth/callback': typeof PublicOauthCallbackRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/financial/': typeof AuthenticatedFinancialIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/sbir/': typeof AuthenticatedSbirIndexRoute
  '/_authenticated/compliance/certifications/$certificationId': typeof AuthenticatedComplianceCertificationsCertificationIdRoute
  '/_authenticated/financial/budgets/$budgetId': typeof AuthenticatedFinancialBudgetsBudgetIdRoute
  '/_authenticated/financial/invoices/$invoiceId': typeof AuthenticatedFinancialInvoicesInvoiceIdRoute
  '/_authenticated/compliance/certifications/': typeof AuthenticatedComplianceCertificationsIndexRoute
  '/_authenticated/financial/budgets/': typeof AuthenticatedFinancialBudgetsIndexRoute
  '/_authenticated/financial/invoices/': typeof AuthenticatedFinancialInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/audit-log'
    | '/billing'
    | '/documents'
    | '/mfa-setup'
    | '/opportunities'
    | '/pipeline'
    | '/settings'
    | '/usage'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/user-roles'
    | '/compliance/clearances'
    | '/compliance/sbom'
    | '/contracts/$contractId'
    | '/crm/contacts'
    | '/crm/interactions'
    | '/crm/organizations'
    | '/financial/labor-rates'
    | '/naics/$naicsCode'
    | '/opportunities/map'
    | '/opportunities/presolicitation'
    | '/opportunities/solicitation'
    | '/opportunities/sources-sought'
    | '/portal/features'
    | '/portal/messaging'
    | '/portal/milestones'
    | '/portal/scope'
    | '/portal/sprints'
    | '/reports/builder'
    | '/sbir/awards'
    | '/oauth/callback'
    | '/compliance/'
    | '/contracts/'
    | '/financial/'
    | '/portal/'
    | '/reports/'
    | '/sbir/'
    | '/compliance/certifications/$certificationId'
    | '/financial/budgets/$budgetId'
    | '/financial/invoices/$invoiceId'
    | '/compliance/certifications/'
    | '/financial/budgets/'
    | '/financial/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/audit-log'
    | '/billing'
    | '/documents'
    | '/mfa-setup'
    | '/opportunities'
    | '/pipeline'
    | '/settings'
    | '/usage'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/user-roles'
    | '/compliance/clearances'
    | '/compliance/sbom'
    | '/contracts/$contractId'
    | '/crm/contacts'
    | '/crm/interactions'
    | '/crm/organizations'
    | '/financial/labor-rates'
    | '/naics/$naicsCode'
    | '/opportunities/map'
    | '/opportunities/presolicitation'
    | '/opportunities/solicitation'
    | '/opportunities/sources-sought'
    | '/portal/features'
    | '/portal/messaging'
    | '/portal/milestones'
    | '/portal/scope'
    | '/portal/sprints'
    | '/reports/builder'
    | '/sbir/awards'
    | '/oauth/callback'
    | '/compliance'
    | '/contracts'
    | '/financial'
    | '/portal'
    | '/reports'
    | '/sbir'
    | '/compliance/certifications/$certificationId'
    | '/financial/budgets/$budgetId'
    | '/financial/invoices/$invoiceId'
    | '/compliance/certifications'
    | '/financial/budgets'
    | '/financial/invoices'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/audit-log'
    | '/_authenticated/billing'
    | '/_authenticated/documents'
    | '/_authenticated/mfa-setup'
    | '/_authenticated/opportunities'
    | '/_authenticated/pipeline'
    | '/_authenticated/settings'
    | '/_authenticated/usage'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/register'
    | '/_public/reset-password'
    | '/_public/verify-email'
    | '/_authenticated/'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/user-roles'
    | '/_authenticated/compliance/clearances'
    | '/_authenticated/compliance/sbom'
    | '/_authenticated/contracts/$contractId'
    | '/_authenticated/crm/contacts'
    | '/_authenticated/crm/interactions'
    | '/_authenticated/crm/organizations'
    | '/_authenticated/financial/labor-rates'
    | '/_authenticated/naics/$naicsCode'
    | '/_authenticated/opportunities/map'
    | '/_authenticated/opportunities/presolicitation'
    | '/_authenticated/opportunities/solicitation'
    | '/_authenticated/opportunities/sources-sought'
    | '/_authenticated/portal/features'
    | '/_authenticated/portal/messaging'
    | '/_authenticated/portal/milestones'
    | '/_authenticated/portal/scope'
    | '/_authenticated/portal/sprints'
    | '/_authenticated/reports/builder'
    | '/_authenticated/sbir/awards'
    | '/_public/oauth/callback'
    | '/_authenticated/compliance/'
    | '/_authenticated/contracts/'
    | '/_authenticated/financial/'
    | '/_authenticated/portal/'
    | '/_authenticated/reports/'
    | '/_authenticated/sbir/'
    | '/_authenticated/compliance/certifications/$certificationId'
    | '/_authenticated/financial/budgets/$budgetId'
    | '/_authenticated/financial/invoices/$invoiceId'
    | '/_authenticated/compliance/certifications/'
    | '/_authenticated/financial/budgets/'
    | '/_authenticated/financial/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mfa-setup': {
      id: '/_authenticated/mfa-setup'
      path: '/mfa-setup'
      fullPath: '/mfa-setup'
      preLoaderRoute: typeof AuthenticatedMfaSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sbir/': {
      id: '/_authenticated/sbir/'
      path: '/sbir'
      fullPath: '/sbir/'
      preLoaderRoute: typeof AuthenticatedSbirIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/': {
      id: '/_authenticated/financial/'
      path: '/financial'
      fullPath: '/financial/'
      preLoaderRoute: typeof AuthenticatedFinancialIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/oauth/callback': {
      id: '/_public/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof PublicOauthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/sbir/awards': {
      id: '/_authenticated/sbir/awards'
      path: '/sbir/awards'
      fullPath: '/sbir/awards'
      preLoaderRoute: typeof AuthenticatedSbirAwardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/builder': {
      id: '/_authenticated/reports/builder'
      path: '/reports/builder'
      fullPath: '/reports/builder'
      preLoaderRoute: typeof AuthenticatedReportsBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/sprints': {
      id: '/_authenticated/portal/sprints'
      path: '/portal/sprints'
      fullPath: '/portal/sprints'
      preLoaderRoute: typeof AuthenticatedPortalSprintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/scope': {
      id: '/_authenticated/portal/scope'
      path: '/portal/scope'
      fullPath: '/portal/scope'
      preLoaderRoute: typeof AuthenticatedPortalScopeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/milestones': {
      id: '/_authenticated/portal/milestones'
      path: '/portal/milestones'
      fullPath: '/portal/milestones'
      preLoaderRoute: typeof AuthenticatedPortalMilestonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/messaging': {
      id: '/_authenticated/portal/messaging'
      path: '/portal/messaging'
      fullPath: '/portal/messaging'
      preLoaderRoute: typeof AuthenticatedPortalMessagingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/features': {
      id: '/_authenticated/portal/features'
      path: '/portal/features'
      fullPath: '/portal/features'
      preLoaderRoute: typeof AuthenticatedPortalFeaturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opportunities/sources-sought': {
      id: '/_authenticated/opportunities/sources-sought'
      path: '/sources-sought'
      fullPath: '/opportunities/sources-sought'
      preLoaderRoute: typeof AuthenticatedOpportunitiesSourcesSoughtRouteImport
      parentRoute: typeof AuthenticatedOpportunitiesRoute
    }
    '/_authenticated/opportunities/solicitation': {
      id: '/_authenticated/opportunities/solicitation'
      path: '/solicitation'
      fullPath: '/opportunities/solicitation'
      preLoaderRoute: typeof AuthenticatedOpportunitiesSolicitationRouteImport
      parentRoute: typeof AuthenticatedOpportunitiesRoute
    }
    '/_authenticated/opportunities/presolicitation': {
      id: '/_authenticated/opportunities/presolicitation'
      path: '/presolicitation'
      fullPath: '/opportunities/presolicitation'
      preLoaderRoute: typeof AuthenticatedOpportunitiesPresolicitationRouteImport
      parentRoute: typeof AuthenticatedOpportunitiesRoute
    }
    '/_authenticated/opportunities/map': {
      id: '/_authenticated/opportunities/map'
      path: '/map'
      fullPath: '/opportunities/map'
      preLoaderRoute: typeof AuthenticatedOpportunitiesMapRouteImport
      parentRoute: typeof AuthenticatedOpportunitiesRoute
    }
    '/_authenticated/naics/$naicsCode': {
      id: '/_authenticated/naics/$naicsCode'
      path: '/naics/$naicsCode'
      fullPath: '/naics/$naicsCode'
      preLoaderRoute: typeof AuthenticatedNaicsNaicsCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/labor-rates': {
      id: '/_authenticated/financial/labor-rates'
      path: '/financial/labor-rates'
      fullPath: '/financial/labor-rates'
      preLoaderRoute: typeof AuthenticatedFinancialLaborRatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/organizations': {
      id: '/_authenticated/crm/organizations'
      path: '/crm/organizations'
      fullPath: '/crm/organizations'
      preLoaderRoute: typeof AuthenticatedCrmOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/interactions': {
      id: '/_authenticated/crm/interactions'
      path: '/crm/interactions'
      fullPath: '/crm/interactions'
      preLoaderRoute: typeof AuthenticatedCrmInteractionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/contacts': {
      id: '/_authenticated/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof AuthenticatedCrmContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/$contractId': {
      id: '/_authenticated/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/sbom': {
      id: '/_authenticated/compliance/sbom'
      path: '/compliance/sbom'
      fullPath: '/compliance/sbom'
      preLoaderRoute: typeof AuthenticatedComplianceSbomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/clearances': {
      id: '/_authenticated/compliance/clearances'
      path: '/compliance/clearances'
      fullPath: '/compliance/clearances'
      preLoaderRoute: typeof AuthenticatedComplianceClearancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/user-roles': {
      id: '/_authenticated/admin/user-roles'
      path: '/admin/user-roles'
      fullPath: '/admin/user-roles'
      preLoaderRoute: typeof AuthenticatedAdminUserRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/invoices/': {
      id: '/_authenticated/financial/invoices/'
      path: '/financial/invoices'
      fullPath: '/financial/invoices/'
      preLoaderRoute: typeof AuthenticatedFinancialInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/budgets/': {
      id: '/_authenticated/financial/budgets/'
      path: '/financial/budgets'
      fullPath: '/financial/budgets/'
      preLoaderRoute: typeof AuthenticatedFinancialBudgetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/certifications/': {
      id: '/_authenticated/compliance/certifications/'
      path: '/compliance/certifications'
      fullPath: '/compliance/certifications/'
      preLoaderRoute: typeof AuthenticatedComplianceCertificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/invoices/$invoiceId': {
      id: '/_authenticated/financial/invoices/$invoiceId'
      path: '/financial/invoices/$invoiceId'
      fullPath: '/financial/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedFinancialInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial/budgets/$budgetId': {
      id: '/_authenticated/financial/budgets/$budgetId'
      path: '/financial/budgets/$budgetId'
      fullPath: '/financial/budgets/$budgetId'
      preLoaderRoute: typeof AuthenticatedFinancialBudgetsBudgetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/certifications/$certificationId': {
      id: '/_authenticated/compliance/certifications/$certificationId'
      path: '/compliance/certifications/$certificationId'
      fullPath: '/compliance/certifications/$certificationId'
      preLoaderRoute: typeof AuthenticatedComplianceCertificationsCertificationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedOpportunitiesRouteChildren {
  AuthenticatedOpportunitiesMapRoute: typeof AuthenticatedOpportunitiesMapRoute
  AuthenticatedOpportunitiesPresolicitationRoute: typeof AuthenticatedOpportunitiesPresolicitationRoute
  AuthenticatedOpportunitiesSolicitationRoute: typeof AuthenticatedOpportunitiesSolicitationRoute
  AuthenticatedOpportunitiesSourcesSoughtRoute: typeof AuthenticatedOpportunitiesSourcesSoughtRoute
}

const AuthenticatedOpportunitiesRouteChildren: AuthenticatedOpportunitiesRouteChildren =
  {
    AuthenticatedOpportunitiesMapRoute: AuthenticatedOpportunitiesMapRoute,
    AuthenticatedOpportunitiesPresolicitationRoute:
      AuthenticatedOpportunitiesPresolicitationRoute,
    AuthenticatedOpportunitiesSolicitationRoute:
      AuthenticatedOpportunitiesSolicitationRoute,
    AuthenticatedOpportunitiesSourcesSoughtRoute:
      AuthenticatedOpportunitiesSourcesSoughtRoute,
  }

const AuthenticatedOpportunitiesRouteWithChildren =
  AuthenticatedOpportunitiesRoute._addFileChildren(
    AuthenticatedOpportunitiesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedMfaSetupRoute: typeof AuthenticatedMfaSetupRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRouteWithChildren
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUserRolesRoute: typeof AuthenticatedAdminUserRolesRoute
  AuthenticatedComplianceClearancesRoute: typeof AuthenticatedComplianceClearancesRoute
  AuthenticatedComplianceSbomRoute: typeof AuthenticatedComplianceSbomRoute
  AuthenticatedContractsContractIdRoute: typeof AuthenticatedContractsContractIdRoute
  AuthenticatedCrmContactsRoute: typeof AuthenticatedCrmContactsRoute
  AuthenticatedCrmInteractionsRoute: typeof AuthenticatedCrmInteractionsRoute
  AuthenticatedCrmOrganizationsRoute: typeof AuthenticatedCrmOrganizationsRoute
  AuthenticatedFinancialLaborRatesRoute: typeof AuthenticatedFinancialLaborRatesRoute
  AuthenticatedNaicsNaicsCodeRoute: typeof AuthenticatedNaicsNaicsCodeRoute
  AuthenticatedPortalFeaturesRoute: typeof AuthenticatedPortalFeaturesRoute
  AuthenticatedPortalMessagingRoute: typeof AuthenticatedPortalMessagingRoute
  AuthenticatedPortalMilestonesRoute: typeof AuthenticatedPortalMilestonesRoute
  AuthenticatedPortalScopeRoute: typeof AuthenticatedPortalScopeRoute
  AuthenticatedPortalSprintsRoute: typeof AuthenticatedPortalSprintsRoute
  AuthenticatedReportsBuilderRoute: typeof AuthenticatedReportsBuilderRoute
  AuthenticatedSbirAwardsRoute: typeof AuthenticatedSbirAwardsRoute
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedFinancialIndexRoute: typeof AuthenticatedFinancialIndexRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSbirIndexRoute: typeof AuthenticatedSbirIndexRoute
  AuthenticatedComplianceCertificationsCertificationIdRoute: typeof AuthenticatedComplianceCertificationsCertificationIdRoute
  AuthenticatedFinancialBudgetsBudgetIdRoute: typeof AuthenticatedFinancialBudgetsBudgetIdRoute
  AuthenticatedFinancialInvoicesInvoiceIdRoute: typeof AuthenticatedFinancialInvoicesInvoiceIdRoute
  AuthenticatedComplianceCertificationsIndexRoute: typeof AuthenticatedComplianceCertificationsIndexRoute
  AuthenticatedFinancialBudgetsIndexRoute: typeof AuthenticatedFinancialBudgetsIndexRoute
  AuthenticatedFinancialInvoicesIndexRoute: typeof AuthenticatedFinancialInvoicesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedMfaSetupRoute: AuthenticatedMfaSetupRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRouteWithChildren,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUserRolesRoute: AuthenticatedAdminUserRolesRoute,
  AuthenticatedComplianceClearancesRoute:
    AuthenticatedComplianceClearancesRoute,
  AuthenticatedComplianceSbomRoute: AuthenticatedComplianceSbomRoute,
  AuthenticatedContractsContractIdRoute: AuthenticatedContractsContractIdRoute,
  AuthenticatedCrmContactsRoute: AuthenticatedCrmContactsRoute,
  AuthenticatedCrmInteractionsRoute: AuthenticatedCrmInteractionsRoute,
  AuthenticatedCrmOrganizationsRoute: AuthenticatedCrmOrganizationsRoute,
  AuthenticatedFinancialLaborRatesRoute: AuthenticatedFinancialLaborRatesRoute,
  AuthenticatedNaicsNaicsCodeRoute: AuthenticatedNaicsNaicsCodeRoute,
  AuthenticatedPortalFeaturesRoute: AuthenticatedPortalFeaturesRoute,
  AuthenticatedPortalMessagingRoute: AuthenticatedPortalMessagingRoute,
  AuthenticatedPortalMilestonesRoute: AuthenticatedPortalMilestonesRoute,
  AuthenticatedPortalScopeRoute: AuthenticatedPortalScopeRoute,
  AuthenticatedPortalSprintsRoute: AuthenticatedPortalSprintsRoute,
  AuthenticatedReportsBuilderRoute: AuthenticatedReportsBuilderRoute,
  AuthenticatedSbirAwardsRoute: AuthenticatedSbirAwardsRoute,
  AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedFinancialIndexRoute: AuthenticatedFinancialIndexRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSbirIndexRoute: AuthenticatedSbirIndexRoute,
  AuthenticatedComplianceCertificationsCertificationIdRoute:
    AuthenticatedComplianceCertificationsCertificationIdRoute,
  AuthenticatedFinancialBudgetsBudgetIdRoute:
    AuthenticatedFinancialBudgetsBudgetIdRoute,
  AuthenticatedFinancialInvoicesInvoiceIdRoute:
    AuthenticatedFinancialInvoicesInvoiceIdRoute,
  AuthenticatedComplianceCertificationsIndexRoute:
    AuthenticatedComplianceCertificationsIndexRoute,
  AuthenticatedFinancialBudgetsIndexRoute:
    AuthenticatedFinancialBudgetsIndexRoute,
  AuthenticatedFinancialInvoicesIndexRoute:
    AuthenticatedFinancialInvoicesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicOauthCallbackRoute: typeof PublicOauthCallbackRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicOauthCallbackRoute: PublicOauthCallbackRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
