/**
 * Auto-generated types from OpenAPI specification
 *
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * To regenerate:
 * 1. Start the backend server: ./gradlew bootRun
 * 2. Run: npm run generate:types
 *
 * To save the spec for offline generation:
 *   npm run generate:types:save
 *
 * To generate from saved spec:
 *   npm run generate:types:offline
 */

// Placeholder types - will be replaced by openapi-typescript
// These allow the codebase to compile before types are generated

/**
 * API paths placeholder
 */
export interface paths {
  [path: string]: {
    get?: unknown;
    post?: unknown;
    put?: unknown;
    delete?: unknown;
    patch?: unknown;
  };
}

/**
 * API components placeholder
 */
export interface components {
  schemas: {
    [name: string]: unknown;
  };
  responses?: {
    [name: string]: unknown;
  };
  parameters?: {
    [name: string]: unknown;
  };
  requestBodies?: {
    [name: string]: unknown;
  };
}

/**
 * Common API response types (manually maintained for convenience)
 */

export interface PageResponse<T> {
  content: T[];
  pageable: {
    pageNumber: number;
    pageSize: number;
    sort: {
      sorted: boolean;
      unsorted: boolean;
      empty: boolean;
    };
  };
  totalElements: number;
  totalPages: number;
  last: boolean;
  first: boolean;
  numberOfElements: number;
  empty: boolean;
}

export interface ErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path: string;
}

export interface AuthenticationResponse {
  accessToken: string;
  refreshToken: string;
  user: UserDto;
  mfaRequired?: boolean;
}

export interface UserDto {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  status: 'ACTIVE' | 'INACTIVE' | 'PENDING' | 'LOCKED';
  emailVerified: boolean;
  mfaEnabled: boolean;
  createdAt: string;
  lastLoginAt?: string;
}
